library(shiny)
library(bslib)
library(ggplot2)
library(readr)
library(dplyr)

# ============================================================
# RLifeHistory Remote Console v4
# ------------------------------------------------------------
# - Keeps the v3.2 detached background NIMBLE runner.
# - Reads REAL output CSV files generated by the existing vignette.
# - Shows WAIC comparison, change-point probabilities, convergence,
#   posterior model curves, and the completed HTML report.
# - No change to the statistical model.
# ============================================================

possible_paths <- c(
  "data/AusData.csv", "../data/AusData.csv", "AusData.csv",
  "../AusData.csv", "AUS.csv", "../AUS.csv"
)
existing_paths <- possible_paths[file.exists(possible_paths)]
aus <- if (length(existing_paths)) {
  read_csv(existing_paths[1], show_col_types = FALSE)
} else {
  NULL
}

status_dir <- "run_status"
status_file <- file.path(status_dir, "latest.txt")
log_file <- file.path(status_dir, "latest.log")
report_file <- "AusData_simple_NIMBLE_slope_models.html"

comparison_file <- file.path("output", "model_comparison_WAIC.csv")
slope_file <- file.path("output", "slope_probabilities.csv")
rhat_file <- file.path("output", "convergence_Rhat.csv")
curves_file <- file.path("output", "posterior_model_curves.csv")
best_curve_png <- file.path("output", "best_model_posterior_curve.png")
slope_png <- file.path("output", "slope_toward_present.png")

read_status <- function() {
  if (!file.exists(status_file)) {
    return(list(status = "READY"))
  }

  z <- readLines(status_file, warn = FALSE)
  parts <- strsplit(z, "=", fixed = TRUE)
  keys <- vapply(parts, `[`, character(1), 1)
  vals <- vapply(
    parts,
    function(x) paste(x[-1], collapse = "="),
    character(1)
  )

  as.list(setNames(vals, keys))
}

safe_csv <- function(path) {
  if (!file.exists(path)) {
    return(NULL)
  }

  tryCatch(
    read.csv(path, stringsAsFactors = FALSE, check.names = FALSE),
    error = function(e) NULL
  )
}

fmt_num <- function(x, digits = 3) {
  if (length(x) == 0 || is.na(x) || !is.finite(x)) {
    return("—")
  }
  formatC(x, format = "f", digits = digits)
}

ui <- page_navbar(
  title = "RLifeHistory",

  nav_panel(
    "Data",

    card(
      card_header("Australian radiocarbon data"),

      if (is.null(aus)) {
        p(
          "AusData.csv was not found here. ",
          "The NIMBLE vignette can still run from AusData.xlsx."
        )
      } else {
        tagList(
          layout_column_wrap(
            width = 1/2,

            value_box(
              title = "Rows loaded",
              value = nrow(aus)
            ),

            value_box(
              title = "Variables",
              value = ncol(aus)
            )
          ),

          plotOutput(
            "data_plot",
            height = "430px"
          )
        )
      },

      full_screen = TRUE
    )
  ),

  nav_panel(
    "Run",

    layout_sidebar(
      sidebar = sidebar(
        radioButtons(
          "run_mode",
          "Run length",
          choices = c(
            "Test" = "test",
            "Medium" = "medium",
            "Long" = "long"
          ),
          selected = "test"
        ),

        actionButton(
          "run_job",
          "RUN NIMBLE ANALYSIS",
          class = "btn-primary"
        ),

        hr(),

        p(
          "Runs the existing NIMBLE vignette in a separate ",
          "R process on the desktop."
        )
      ),

      card(
        card_header("Desktop job status"),
        uiOutput("job_status"),
        actionButton("refresh", "Refresh status")
      ),

      card(
        card_header("Latest log"),
        verbatimTextOutput("job_log")
      )
    )
  ),

  nav_panel(
    "Results",

    uiOutput("results_header"),

    layout_column_wrap(
      width = 1/3,

      value_box(
        title = "Best model",
        value = textOutput("best_model", inline = TRUE)
      ),

      value_box(
        title = "ΔWAIC",
        value = textOutput("delta_waic", inline = TRUE)
      ),

      value_box(
        title = "Change point",
        value = textOutput("change_point", inline = TRUE)
      )
    ),

    card(
      card_header("WAIC model comparison"),
      tableOutput("waic_table"),
      full_screen = TRUE
    ),

    card(
      card_header("Posterior demographic curves"),
      plotOutput(
        "posterior_curve",
        height = "480px"
      ),
      full_screen = TRUE
    ),

    layout_column_wrap(
      width = 1/2,

      card(
        card_header("Direct slope questions"),
        tableOutput("slope_table")
      ),

      card(
        card_header("Convergence diagnostics"),
        tableOutput("rhat_table")
      )
    ),

    card(
      card_header("Completed report"),
      uiOutput("report_status"),
      downloadButton(
        "download_report",
        "Download full HTML report"
      )
    )
  ),

  nav_panel(
    "Files",

    card(
      card_header("Generated output files"),
      uiOutput("output_files")
    )
  )
)

server <- function(input, output, session) {

  output$data_plot <- renderPlot({
    req(!is.null(aus))

    dat <- aus

    numeric_cols <- names(dat)[
      vapply(dat, is.numeric, logical(1))
    ]

    validate(
      need(
        length(numeric_cols) >= 1,
        "No numeric columns found."
      )
    )

    likely_age <- grep(
      "age|date|c14|bp",
      numeric_cols,
      ignore.case = TRUE,
      value = TRUE
    )

    age_col <- if (length(likely_age)) {
      likely_age[1]
    } else {
      numeric_cols[1]
    }

    plot_dat <- data.frame(
      Index = seq_len(nrow(dat)),
      Age = dat[[age_col]]
    )

    ggplot(
      plot_dat,
      aes(Index, Age)
    ) +
      geom_point(
        size = 2,
        alpha = 0.7
      ) +
      labs(
        title = paste(
          "Using column:",
          age_col
        ),
        x = "Record",
        y = age_col
      ) +
      theme_minimal(
        base_size = 16
      )
  })

  observeEvent(input$run_job, {
    st <- read_status()

    if (
      !is.null(st$status) &&
      identical(st$status, "RUNNING")
    ) {
      showNotification(
        "A NIMBLE job is already marked as running.",
        type = "warning"
      )
      return()
    }

    req(
      file.exists(
        "AusData_simple_NIMBLE_slope_models.Rmd"
      )
    )
    req(file.exists("run_shiny_job.R"))
    req(file.exists("AusData.xlsx"))

    dir.create(
      status_dir,
      showWarnings = FALSE,
      recursive = TRUE
    )

    # Do not try to delete an actively locked log.
    if (file.exists(log_file)) {
      try(
        unlink(log_file),
        silent = TRUE
      )
    }

    rscript <- file.path(
      R.home("bin"),
      "Rscript.exe"
    )

    if (!file.exists(rscript)) {
      rscript <- file.path(
        R.home("bin"),
        "Rscript"
      )
    }

    rscript <- normalizePath(
      rscript,
      winslash = "\\",
      mustWork = TRUE
    )

    worker <- normalizePath(
      "run_shiny_job.R",
      winslash = "\\",
      mustWork = TRUE
    )

    logfile_abs <- normalizePath(
      status_dir,
      winslash = "\\",
      mustWork = TRUE
    )

    logfile_abs <- file.path(
      logfile_abs,
      "latest.log"
    )

    system2(
      command = rscript,
      args = c(
        shQuote(worker),
        input$run_mode
      ),
      stdout = logfile_abs,
      stderr = logfile_abs,
      wait = FALSE,
      invisible = TRUE
    )

    showNotification(
      paste(
        "Started",
        input$run_mode,
        "analysis on desktop."
      ),
      type = "message"
    )
  })

  output$job_status <- renderUI({
    input$refresh
    invalidateLater(3000, session)

    st <- read_status()
    status <- if (is.null(st$status)) {
      "UNKNOWN"
    } else {
      st$status
    }

    cls <- switch(
      status,
      RUNNING = "alert alert-warning",
      FINISHED = "alert alert-success",
      ERROR = "alert alert-danger",
      "alert alert-secondary"
    )

    tags$div(
      class = cls,
      tags$h4(status),

      if (!is.null(st$mode)) {
        tags$p(
          paste("Mode:", st$mode)
        )
      },

      if (!is.null(st$started)) {
        tags$p(
          paste("Started:", st$started)
        )
      },

      if (!is.null(st$finished)) {
        tags$p(
          paste("Finished:", st$finished)
        )
      },

      if (!is.null(st$error)) {
        tags$p(
          paste("Error:", st$error)
        )
      }
    )
  })

  output$job_log <- renderText({
    input$refresh
    invalidateLater(5000, session)

    if (!file.exists(log_file)) {
      return("No job log yet.")
    }

    tryCatch(
      {
        x <- readLines(
          log_file,
          warn = FALSE
        )

        if (length(x) == 0) {
          "Log exists but is currently empty."
        } else {
          paste(
            tail(x, 40),
            collapse = "\n"
          )
        }
      },
      error = function(e) {
        st <- read_status()

        if (
          !is.null(st$status) &&
          identical(st$status, "RUNNING")
        ) {
          paste(
            "Analysis is running.",
            "Windows has temporarily locked the live log."
          )
        } else if (
          !is.null(st$status) &&
          identical(st$status, "FINISHED")
        ) {
          paste(
            "Analysis finished.",
            "The log is temporarily locked,",
            "but the results are available."
          )
        } else {
          paste(
            "Log temporarily unavailable:",
            conditionMessage(e)
          )
        }
      }
    )
  })

  comparison <- reactive({
    input$refresh
    invalidateLater(5000, session)
    safe_csv(comparison_file)
  })

  slopes <- reactive({
    input$refresh
    invalidateLater(5000, session)
    safe_csv(slope_file)
  })

  rhats <- reactive({
    input$refresh
    invalidateLater(5000, session)
    safe_csv(rhat_file)
  })

  curves <- reactive({
    input$refresh
    invalidateLater(5000, session)
    safe_csv(curves_file)
  })

  output$results_header <- renderUI({
    st <- read_status()

    if (
      !is.null(st$status) &&
      identical(st$status, "FINISHED")
    ) {
      tags$div(
        class = "alert alert-success",
        tags$strong(
          "Latest NIMBLE analysis finished successfully."
        ),
        tags$br(),
        if (!is.null(st$mode)) {
          paste("Run mode:", st$mode)
        },
        if (!is.null(st$finished)) {
          paste(" • Finished:", st$finished)
        }
      )
    } else if (
      !is.null(st$status) &&
      identical(st$status, "RUNNING")
    ) {
      tags$div(
        class = "alert alert-warning",
        "NIMBLE analysis is currently running."
      )
    } else {
      tags$div(
        class = "alert alert-secondary",
        paste(
          "Showing the most recent output files",
          "currently available."
        )
      )
    }
  })

  output$best_model <- renderText({
    dat <- comparison()

    if (
      is.null(dat) ||
      !all(c("model", "WAIC") %in% names(dat))
    ) {
      return("—")
    }

    dat <- dat[
      is.finite(dat$WAIC),
      ,
      drop = FALSE
    ]

    if (!nrow(dat)) {
      return("WAIC unavailable")
    }

    dat$model[
      which.min(dat$WAIC)
    ]
  })

  output$delta_waic <- renderText({
    dat <- comparison()

    if (
      is.null(dat) ||
      !"delta_WAIC" %in% names(dat)
    ) {
      return("—")
    }

    vals <- sort(
      unique(
        dat$delta_WAIC[
          is.finite(dat$delta_WAIC)
        ]
      )
    )

    vals <- vals[vals > 0]

    if (!length(vals)) {
      return("—")
    }

    fmt_num(vals[1], 2)
  })

  output$change_point <- renderText({
    dat <- slopes()

    if (
      is.null(dat) ||
      !all(c("quantity", "value") %in% names(dat))
    ) {
      return("—")
    }

    idx <- match(
      "Median change point cal AD",
      dat$quantity
    )

    if (is.na(idx)) {
      return("—")
    }

    paste0(
      "AD ",
      round(dat$value[idx])
    )
  })

  output$waic_table <- renderTable({
    dat <- comparison()

    validate(
      need(
        !is.null(dat),
        "No WAIC output yet. Run the analysis first."
      )
    )

    dat
  }, digits = 3)

  output$slope_table <- renderTable({
    dat <- slopes()

    validate(
      need(
        !is.null(dat),
        "No slope-probability output yet."
      )
    )

    dat
  }, digits = 4)

  output$rhat_table <- renderTable({
    dat <- rhats()

    validate(
      need(
        !is.null(dat),
        "No convergence output yet."
      )
    )

    dat
  }, digits = 3)

  output$posterior_curve <- renderPlot({
    dat <- curves()

    validate(
      need(
        !is.null(dat),
        paste(
          "No posterior curve output yet.",
          "Run the analysis first."
        )
      )
    )

    required <- c(
      "calendar_display_value",
      "median",
      "lower",
      "upper",
      "model"
    )

    validate(
      need(
        all(required %in% names(dat)),
        "Posterior curve CSV has unexpected columns."
      )
    )

    ggplot(
      dat,
      aes(
        x = calendar_display_value,
        y = median,
        linetype = model
      )
    ) +
      geom_ribbon(
        aes(
          ymin = lower,
          ymax = upper,
          group = model
        ),
        alpha = 0.15,
        inherit.aes = TRUE
      ) +
      geom_line(
        linewidth = 1
      ) +
      labs(
        title = "Posterior demographic slope shapes",
        subtitle = "Median curves with 95% credible intervals",
        x = "Calendar date",
        y = "Relative date-density",
        linetype = "Model"
      ) +
      theme_minimal(
        base_size = 14
      ) +
      theme(
        legend.position = "bottom"
      )
  })

  output$report_status <- renderUI({
    input$refresh
    invalidateLater(5000, session)

    if (file.exists(report_file)) {
      tags$div(
        class = "alert alert-success",
        tags$strong(
          "Full HTML report is available."
        ),
        tags$br(),
        paste(
          "Last modified:",
          format(
            file.info(report_file)$mtime
          )
        )
      )
    } else {
      tags$div(
        class = "alert alert-secondary",
        "No completed HTML report found yet."
      )
    }
  })

  output$download_report <- downloadHandler(
    filename = function() {
      paste0(
        "RLifeHistory_",
        Sys.Date(),
        ".html"
      )
    },

    content = function(file) {
      req(file.exists(report_file))

      file.copy(
        report_file,
        file,
        overwrite = TRUE
      )
    }
  )

  output$output_files <- renderUI({
    input$refresh
    invalidateLater(5000, session)

    files <- c(
      comparison_file,
      slope_file,
      rhat_file,
      curves_file,
      best_curve_png,
      slope_png,
      report_file
    )

    labels <- c(
      "WAIC model comparison",
      "Slope probabilities / change point",
      "R-hat convergence diagnostics",
      "Posterior model curves",
      "Best-model posterior curve",
      "Slope toward present",
      "Full HTML report"
    )

    items <- lapply(
      seq_along(files),
      function(i) {
        exists <- file.exists(files[i])

        tags$li(
          tags$strong(labels[i]),
          " — ",
          if (exists) {
            paste(
              "available •",
              format(
                file.info(files[i])$mtime
              )
            )
          } else {
            "not yet available"
          }
        )
      }
    )

    tags$ul(items)
  })
}

shinyApp(ui, server)
